let catData={"categories":[
{"category":"Deviazione", "colour":"#b78c0b",
    "description":"Enfatizza le variazioni (+/-) da un punto di riferimento fisso. In genere il punto di riferimento è zero ma può anche essere una destinazione o una media a lungo termine. Può essere utilizzato anche per mostrare il sentimento (positivo / neutro / negativo)",
    "example":"surplus / deficit commerciale, cambiamenti climatici"},
{"category":"Correlazione", "colour":"#977348",
    "description":"Mostra la relazione tra due o più variabili. Siate consapevoli che, a meno che non sia diversamente specificato, genericamente la comprensione dell'utente assume che le relazioni siano causali (cioè una causa l'altra)",
    "example":"Inflazione e disoccupazione, reddito e aspettativa di vita"},
{"category":"Variazione", "colour":"#28903B",
	"description":"Impiegato per dare enfasi al cambiamento delle tendenze. Queste possono essere brevi (es. stesso giorno) movimenti o serie estese che attraversano decenni o secoli: la scelta del periodo di tempo corretto è importante per fornire un contesto adatto",
	"example":"Variazione dei prezzi azionari, serie temporali economiche"},
{"category":"Classificazione", "colour":"#008EB0",
    "description":"Da impiegare quanto la posizione di un oggetto in un elenco ordinato è più importante del suo valore assoluto o relativo. Non aver paura di evidenziare i punti di interesse.",
    "example":"Ricchezza, privazione, classifiche, risultati delle elezioni locali"},
{"category":"Distribuzione", "colour":"#F26522",
	"description":"Mostra i valori in un set di dati e quanto spesso si verificano. La forma (o 'inclinazione') di una distribuzione può essere un modo memorabile di evidenziare la mancanza di uniformità o uguaglianza nei dati",
	"example":"Distribuzione del reddito, distribuzione della popolazione (età / sesso)"},
{"category":"Partizione", "colour":"#0054A6",
    "description":"Mostra come una singola entità può essere scomposta nei suoi elementi componenti. Se l'interesse è unicamente di evidenziare la dimensione dei componenti, considera invece un grafico di tipo magnitudo",
    "example":"Budget fiscali, strutture aziendali, risultati delle elezioni nazionali"},
{"category":"Magnitudine", "colour":"#A3488C",
    "description":"Mostra il confronti tra le dimensioni. Queste possono essere relative (solo in grado di vedere le più grandi / la più grande) o assoluto (è necessario vedere le differenze). Di solito utilizzare per mostrare una quantità fisica (ad esempio, barili, euro o persone) piuttosto che un tasso calcolato o percentuale",
    "example":"Produzione di materie prime, capitalizzazione di mercato"},
{"category":"Spaziale", "colour":"#9C9D94",
    "description":"Utilizzato sopratutto quando posizioni precise o schemi geografici dei dati sono più importanti di qualsiasi altra cosa. La componente geografica o spaziale è quindi di rilievo rispetto al resto dei dati",
    "example":"Mappe di localizzazione, densità di popolazione, ubicazioni di risorse naturali, rischio / impatto di disastri naturali, aree di bacino idrico, variazione dei risultati elettorali"},
{"category":"Flusso", "colour":"#ABBD67",
    "description":"Mostra il volume o l'intensità del movimento tra due o più stati o condizioni. Queste potrebbero essere anche sequenze logiche, temporali o posizioni nello spazio o geografiche",
    "example":"Movimento di fondi, commercio, migranti, cause legali, informazioni; grafici di relazione"}]
}

